name = "strivetrackapp"
pages_build_output_dir = "public"
compatibility_date = "2024-09-07"
compatibility_flags = ["nodejs_compat"]

# Ensure functions are properly configured
[build]
command = ""

[build.environment]
NODE_VERSION = "18"

[[d1_databases]]
binding = "DB"
database_name = "strivetrack"
database_id = "d8ff189a-65d6-4c62-8637-02977cc9e0e7"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "strivetrack-media"

[vars]
ADMIN_EMAIL = "iamhollywoodpro@protonmail.com"
ADMIN_PASSWORD = "iampassword@1981"
ENVIRONMENT = "production"

[env.preview]
name = "strivetrack-preview"
[[env.preview.d1_databases]]
binding = "DB"
database_name = "strivetrack"
database_id = "d8ff189a-65d6-4c62-8637-02977cc9e0e7"

[[env.preview.r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "strivetrack-media"

[env.preview.vars]
ADMIN_EMAIL = "iamhollywoodpro@protonmail.com"
ADMIN_PASSWORD = "iampassword@1981"
ENVIRONMENT = "preview"

[env.production]
name = "strivetrack"
[[env.production.d1_databases]]
binding = "DB"
database_name = "strivetrack"
database_id = "d8ff189a-65d6-4c62-8637-02977cc9e0e7"

[[env.production.r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "strivetrack-media"

[env.production.vars]
ADMIN_EMAIL = "iamhollywoodpro@protonmail.com"
ADMIN_PASSWORD = "iampassword@1981"
ENVIRONMENT = "production"