name = "strivetrack"
main = "functions/_middleware.js"
compatibility_date = "2023-08-07"

[env.development]
name = "strivetrack-dev"

[env.production]
name = "strivetrack"

[[d1_databases]]
binding = "DB"
database_name = "strivetrack"
database_id = "b497cf67-d4c1-4cb5-b60a-aa574fe5b9cb"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "strivetrack-media"

[vars]
ADMIN_EMAIL = "iamhollywoodpro@protonmail.com"
ADMIN_PASSWORD = "password123"
ENVIRONMENT = "development"